export const MOCK_VEHICLE = {
  id:              'U-0142',
  unitId:          'U-0142',
  vin:             '8AFED71B5LA247892',
  plate:           'SBQ 3812',
  make:            'Toyota',
  model:           'Hilux',
  year:            2022,
  color:           'Silver',
  category:        'Pickup',
  locationName:    'Loc A · Punta del Este',
  status:          'assigned' as const,
  odometer:        47284,
  odometerAtEntry: 247,
  fuelLevel:       82,
  fuelType:        'Diesel',
  engineType:      'Combustion',
  displacement:    '2.8L Turbo',
  transmission:    'Manual 6-speed',
  driveType:       '4WD',
  tankCapacity:    80,
  tireSize:        '265/65 R17',
  seatingCapacity: 5,
  cargoVolume:     '0.94 m³',
  towRating:       '3,500 kg',
  acquisitionDate: '2022-03-15',
  acquisitionCost: 42500,
  hasGps:            true,
  hasDashcam:        true,
  hasTollTag:        false,
  hasTowHook:        true,
  hasIsofix:         false,
  hasWheelchairLift: false,
  hasRoofRack:       true,
  hasRefrigeration:  false,
  hasWorkVan:        false,
  gpsProvider:      'Tracksolid',
  gpsDeviceId:      'TS-2847501',
  dashcamChannels:  '2-channel (front + rear)',
  dashcamStorage:   '64 GB',
  towHookCapacity:  '3,500 kg',
  roofRackLoad:     '100 kg',
  lastServiceType:        '5,000 km Service',
  lastServiceDate:        '2026-04-27',
  lastServiceOdometer:    45000,
  lastServiceDealer:      'Toyota Punta del Este',
  lastServiceStamp:       'STM-2026-04-PDE',
  lastServiceDocumentUrl: '#',
}

export const MOCK_DOCUMENTS = [
  { type: 'Insurance Certificate', issuer: 'MAPFRE Uruguay', fileUrl: '#', expiry: '2026-08-20' },
  { type: 'Vehicle Registration',  issuer: 'Ministerio de Transporte', fileUrl: '#', expiry: '2026-05-28' },
  { type: 'Technical Inspection',  issuer: 'LATU Montevideo', fileUrl: '#', expiry: '2026-05-10' },
  { type: 'GPS Equipment Cert.',   issuer: 'Tracksolid UY', fileUrl: '#', expiry: '2026-11-15' },
]

export type MockVehicle = typeof MOCK_VEHICLE
export type MockDocument = typeof MOCK_DOCUMENTS[number]
